from __future__ import annotations

from run4221.events import TrackedEvent


def sample_seed_events() -> tuple[TrackedEvent, ...]:
    return (
        TrackedEvent(
            id="berlin-marathon",
            public_id="berlin.42",
            legacy_ids=("berlin-marathon",),
            search_keywords=("bmw berlin marathon", "berlin"),
            name="BMW Berlin Marathon",
            city="Berlin",
            country="Germany",
            timezone="Europe/Berlin",
            distances=("marathon",),
            regions=("global", "eu", "de"),
            collections=("world_marathon_majors",),
            event_date="2026-09-27",
            registration_status="unknown",
            official_url="https://example.test/berlin-marathon",
            registration_url="https://example.test/berlin-marathon/register",
        ),
        TrackedEvent(
            id="berlin-half-marathon",
            public_id="berlin.21",
            legacy_ids=("berlin.superhalf.21",),
            search_keywords=("generali berlin half marathon", "berlin"),
            name="Generali Berlin Half Marathon",
            city="Berlin",
            country="Germany",
            timezone="Europe/Berlin",
            distances=("half_marathon",),
            regions=("eu", "de"),
            collections=("superhalfs",),
            event_date="2027-04-04",
            registration_status="unknown",
            official_url="https://example.test/berlin-half-marathon",
            registration_url="https://example.test/berlin-half-marathon/register",
        ),
        TrackedEvent(
            id="lisbon-half-marathon",
            public_id="lisbon.21",
            legacy_ids=(),
            search_keywords=("edp lisbon half marathon",),
            name="EDP Lisbon Half Marathon",
            city="Lisbon",
            country="Portugal",
            timezone="Europe/Lisbon",
            distances=("half_marathon",),
            regions=("eu",),
            collections=("superhalfs",),
            event_date="2026-03-08",
            registration_status="unknown",
            official_url="https://example.test/lisbon-half-marathon",
            registration_url="https://example.test/lisbon-half-marathon/register",
        ),
        TrackedEvent(
            id="prague-half-marathon",
            public_id="prague.21",
            legacy_ids=(),
            search_keywords=("generali prague half marathon",),
            name="Generali Prague Half Marathon",
            city="Prague",
            country="Czech Republic",
            timezone="Europe/Prague",
            distances=("half_marathon",),
            regions=("eu",),
            collections=("superhalfs",),
            event_date="2026-03-28",
            registration_status="unknown",
            official_url="https://example.test/prague-half-marathon",
            registration_url="https://example.test/prague-half-marathon/register",
        ),
        TrackedEvent(
            id="copenhagen-half-marathon",
            public_id="copenhagen.21",
            legacy_ids=(),
            search_keywords=("copenhagen half marathon",),
            name="Copenhagen Half Marathon",
            city="Copenhagen",
            country="Denmark",
            timezone="Europe/Copenhagen",
            distances=("half_marathon",),
            regions=("eu",),
            collections=("superhalfs",),
            event_date="2026-09-20",
            registration_status="unknown",
            official_url="https://example.test/copenhagen-half-marathon",
            registration_url="https://example.test/copenhagen-half-marathon/register",
        ),
        TrackedEvent(
            id="boston-marathon",
            public_id="boston.42",
            legacy_ids=(),
            search_keywords=("boston marathon",),
            name="Boston Marathon",
            city="Boston",
            country="United States",
            timezone="America/New_York",
            distances=("marathon",),
            regions=("global", "us"),
            collections=("world_marathon_majors",),
            event_date=None,
            registration_status="unknown",
            official_url="https://example.test/boston-marathon",
            registration_url="https://example.test/boston-marathon/register",
        ),
        TrackedEvent(
            id="chicago-marathon",
            public_id="chicago.42",
            legacy_ids=(),
            search_keywords=("chicago marathon",),
            name="Bank of America Chicago Marathon",
            city="Chicago",
            country="United States",
            timezone="America/Chicago",
            distances=("marathon",),
            regions=("global", "us"),
            collections=("world_marathon_majors",),
            event_date=None,
            registration_status="unknown",
            official_url="https://example.test/chicago-marathon",
            registration_url="https://example.test/chicago-marathon/register",
        ),
        TrackedEvent(
            id="new-york-city-marathon",
            public_id="nyc.42",
            legacy_ids=(),
            search_keywords=("new york city marathon", "nyc marathon"),
            name="TCS New York City Marathon",
            city="New York City",
            country="United States",
            timezone="America/New_York",
            distances=("marathon",),
            regions=("global", "us"),
            collections=("world_marathon_majors",),
            event_date=None,
            registration_status="unknown",
            official_url="https://example.test/nyc-marathon",
            registration_url="https://example.test/nyc-marathon/register",
        ),
    )
